### ISSUE TITLE
Inject polymer component inside px-data-table column

### ISSUE THREAD

**Issue by rupeshpadhye** [PredixDev/px-data-table#100]
Hi,
 Currently px-data-table cells are driven by types such as string , dropdown and html but we have requirement where we need to render custom polymer component inside cell.

**Comment by randyaskin** [comment]
You can achieve this with the `html` column type, as long as you've imported the component at the top of the file. Here's an example: http://codepen.io/randyaskin/pen/apexgB?editors=1000

**Comment by rupeshpadhye** [comment]
Thanks a lot  @randyaskin . This will satisfy our current requirement .
