### ISSUE TITLE
Font awesome Issue in the console

### ISSUE THREAD

**Issue by anundinesh** [PredixDev/px-data-table#101]
HI,

We are getting the below error in console, when the data table is loading. our repository
![erroronconsole](https://cloud.githubusercontent.com/assets/20392598/23208946/f54c110a-f8ee-11e6-9a8a-8660c7ecc226.png)
 path is fine something going wrong with the data table dependencies. Could someone look into this?

**Comment by mdwragg** [comment]
Hi,

Thanks for your issue. A couple of things, this defect already exists (#93) and can you please follow the template for creating new issues - the information we are asking for is required to help us recreate and fix the issue.

As mentioned repeatedly in #93, I need steps to recreate this issue (and what browsers it is happening on etc, etc.).

I'll close this duplicate but would like your assistance in helping me recreate #93.

**Comment by anundinesh** [comment]
you can use this http://codepen.io/pen/?editors=1000. Please check the console in this.
