### ISSUE TITLE
Server Side Pagination Request

### ISSUE THREAD

**Issue by harsharnge** [PredixDev/px-data-table#104]
It would be useful to have the ability to use server side pagination with the px-data-table. On the click of previous/next page it should fire an event which will allow us do backend calls for server side pagination.

**Comment by Charlesjwilliams2** [comment]
Exposing the pager element and providing events for using HATEOAS format data sources would be great.

**Comment by randyaskin** [comment]
Will be enabled with #126

**Comment by mdwragg** [comment]
Which is now merged 👍
