### ISSUE TITLE
px-row-click event is not fired for row selection without checkbox

### ISSUE THREAD

**Issue by swapnavad** [PredixDev/px-data-table#109]
# Submit an Issue

Hi,

Thanks for helping us improve the Predix UI platform by submitting an issue.

Before you begin, please check the list of existing issues to avoid submitting a duplicate issue.

To help us solve this issue as fast as possible, please fill out the following sections:

## Expected behavior and actual behavior:
Excepted behavior : Clicking on the row without a checkbox , should fire the px-row-click event, as per documentation.
actual behavior : its px-cell-click event that is fired instead of px-row-click.

## Steps to reproduce the problem:

<px-data-table
        id="metaListTable"
        selectedRows="{{mySelectedItems}}"
        table-data="{{metaDataTableData}}"
        striped="true"
        filterable="true"
        show-column-chooser="true"
        enable-column-reorder="true"
        enable-column-resize="true">
        <px-data-table-column name="Name"></px-data-table-column>
        <px-data-table-column name="Source"></px-data-table-column>
        <px-data-table-column name="Uri"></px-data-table-column>
        <px-data-table-column name="Status" hide="true"></px-data-table-column>
        <px-data-table-column name="Publisher"  hide="true" ></px-data-table-column>
        <px-data-table-column name="Data Modified"  hide="true"></px-data-table-column>
      </px-data-table>

ready: function() {
        console.log('list-metadata ready()')
        this.metaDataPostBody=JSON.stringify(this.restRequestObject);
        this.metaDataUrl='/services/fdhrouter/fielddatahandler/getfielddata';
        console.log(JSON.stringify(this.restRequestObject));
        this.$.metaDataList.body=JSON.stringify(this.restRequestObject);
        this.$.metaDataList.generateRequest();
        this.$.addNewDataSetButton.addEventListener('click', this._addnewDataSet);
  this.$.metaListTable.addEventListener('px-row-click', function(evt) {
          var clickedRow = evt.detail.row;
          console.log("Row clicked px-row-click", clickedRow, " _selected: ", clickedRow._selected);
        });
        this.$.metaListTable.addEventListener('px-cell-click', function(evt) {
          var clickedRow = evt.detail.row;
          console.log("Row clicked px-cell-click", clickedRow, " _selected: ", clickedRow._selected);
        });

## Code examples help us better understand the issue - follow the appropriate codepen for the component by going to https://predix-ui.com, finding the component in question, and clicking on the pencil icon under the demo.
        Once you've created your code example, you can save it under a new url.
        Please note that you should NOT use the same methods for production as the ones used in codepen - these methods are not production ready.

**Comment by randyaskin** [comment]
Fixed in 2.0.0 - clicking on a non-editable / non-dropdown cell now fires px-row-click as well.
