### ISSUE TITLE
v2 tables broken when column is hidden

### ISSUE THREAD

**Issue by davidsteinberger** [PredixDev/px-data-table#114]
## Expected behavior and actual behavior:

Previously it was possible to hide a column by setting the `hide` property. That caused the header- as well as the body-column to be hidden (in sync). It seems to me that a recent change has broken that.

## Steps to reproduce the problem:

use any v2.x.x version of <px-data-table> and set a column to be hidden

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):

any version >= v2.0.0

## Screenshots (_optional, but very helpful_):

![screen shot 2017-03-20 at 23 15 44](https://cloud.githubusercontent.com/assets/385430/24124281/4440d8e8-0dc3-11e7-8790-6a933e355a7f.png)

## Code examples 

https://github.build.ge.com/105042697/px-data-table-114.git

**Comment by randyaskin** [comment]
Interesting. I didn't think altering `hide` ever worked correctly, per #94 - none of the column sub-property changes are observed. Martin and I tried switching to a mutation observer, but it was causing flickering of all of the values. You can still use the `aha-table.hideColumn('first')` method, which is the same way the column chooser does it.

**Comment by davidsteinberger** [comment]
The reason why I created that ticket was that until v1.15.21 a _static_ (not data-bound) hide-property worked fine for us. So the behavior is slightly different than described in #94.

I haven't looked into the root-cause yet, but it's most probably b/c of the sub-property changes. Isn't that a big issue on it's own? E.g. I see no way to properly localize a table right now, like:

    <px-data-table-column name="name" label="[[localize('name')]]"></px-data-table-column

Should there be a separate issue to track that?

**Comment by randyaskin** [comment]
A static "hide" is working fine for me in both my local and on CodePen. http://codepen.io/randyaskin/pen/EWEyab?&editors=1001

I noticed in your screenshot that the "first" column seems to be duplicated. Is that after hiding and re-showing it? I did see some of that while I was iterating on the 2.0.0 version, but I thought I fixed that. I did see some duplicate column behavior on CodePen just now with `include-all-columns` which I'm going to look into.

**Comment by davidsteinberger** [comment]
Yes, I also experienced that kind of duplication. I never know what version codepen pulls, so I created a small repo that replicates the issue [here](https://github.build.ge.com/105042697/px-data-table-114.git). Did u try that (simply run `bower install && python -m SimpleHTTPServer`)?

**Comment by randyaskin** [comment]
I'm trying to run it. The bower install went fine, I see all the dependencies. But when I try to hit localhost:8000 after starting the simple server, I get a bunch of 404 errors and nothing loads. Any ideas?

**Comment by randyaskin** [comment]
Fixed in v2.0.4 - thanks again for your help.
