### ISSUE TITLE
Inconsistent style on pagination dropdown among browsers

### ISSUE THREAD

**Issue by amyerz** [PredixDev/px-data-table#115]
Inconsistent style on pagination dropdown among browsers:
https://www.predix-ui.com/#/components/px-data-table/

Chrome:
![screen shot 2017-03-21 at 4 10 53 pm](https://cloud.githubusercontent.com/assets/4411687/24175024/3eda608e-0e51-11e7-9f5e-0dc263566350.png)

Firefox:
![screen shot 2017-03-21 at 4 11 00 pm](https://cloud.githubusercontent.com/assets/4411687/24175035/47614a06-0e51-11e7-86fd-39a7d3a5105f.png)

Safari:
![screen shot 2017-03-21 at 4 11 33 pm](https://cloud.githubusercontent.com/assets/4411687/24175040/4ec1361c-0e51-11e7-8d9f-1ecdd2f5d4e3.png)

**Comment by randyaskin** [comment]
Yes, that's because it's currently using a generic HTML <select> menu, which differs by browser. I attempted to cut it over to px-dropdown over the weekend but broke a bunch of tests and things and had to revert - I'm working on re-doing those changes.

**Comment by randyaskin** [comment]
Fixed in v4.
