### ISSUE TITLE
Custom page size doesn't reflect Rows per page in Pagination

### ISSUE THREAD

**Issue by amitnarang28** [PredixDev/px-data-table#118]
Hi Team 

if we select custom  page-size in px-data-table component e.g. 5, it changes the pagination to that number but the drop down in pagination next to Rows per page still says 10.

Rows per page should say 5 or number passed as page-size.

## Steps to reproduce the problem:
Current latest version have same issue is clearly visible in complex table example on https://www.predix-ui.com/#/components/px-data-table/

## Screenshots (_optional, but very helpful_):
![px-data-table-issue](https://cloud.githubusercontent.com/assets/1487260/24769627/2711694e-1ad5-11e7-8c94-fb68fdc61374.png)

**Comment by randyaskin** [comment]
Fixed in v4.
