### ISSUE TITLE
Can't add image icons or HTML contents in the table

### ISSUE THREAD

**Issue by anandmedhekar** [PredixDev/px-data-table#124]
## Screenshots (_optional, but very helpful_): 
![image](https://cloud.githubusercontent.com/assets/12048080/25468905/8a89b348-2b36-11e7-8f15-e195641eac7b.png)
Adding Delete icon image
![image](https://cloud.githubusercontent.com/assets/12048080/25468911/96691d5c-2b36-11e7-87a7-9098b337a4c9.png)

**Comment by randyaskin** [comment]
You need to include a `<px-data-table-column type="html">` as a child of your `px-data-table` tag. Here are some examples:

- http://codepen.io/randyaskin/pen/LbOrmY?editors=1010
- http://codepen.io/randyaskin/pen/KgwYpg?editors=1010
- http://codepen.io/randyaskin/pen/apexgB?editors=1010
