### ISSUE TITLE
Long column names cut in column chooser dropdown

### ISSUE THREAD

**Issue by qrwacek** [PredixDev/px-data-table#125]
## Expected behavior and actual behavior
Column chooser dropdown is cut for longer columns names when some column is selected/deselected (check screenshot below). It should always show full name of the column.
Additionally dropdown label is changed from "Show/Hide Column" to "Select". Label should stay unchanged

## Steps to reproduce the problem
Use long column names ("First name", "Last name" or "Email address" is long enough) in table data.
Open column chooser and deselect any column

## Environment
Chrome Version 58.0.3029.81
Windows 7
DELL Laptop

## Screenshots
![px-data-table-dropdown-cut](https://cloud.githubusercontent.com/assets/1021755/25519925/271e8abc-2bfa-11e7-9d47-6fdf25a11567.png)

## Code examples
https://codepen.io/anon/pen/EmWgJW

**Comment by randyaskin** [comment]
Actually a defect in px-dropdown, not px-data-table. Fixed by my component redesign which will be released in June with the rest of the redesigned components. Partially captured [here](https://github.com/PredixDev/px-dropdown/issues/40).
