### ISSUE TITLE
Custom styling property not working with px-data-table

### ISSUE THREAD

**Issue by bhatankit** [PredixDev/px-data-table#127]
# Submit an Issue
Custom styling property not working with px-data-table.
We are trying with putting it with inline css. Please find below the example.

![image](https://cloud.githubusercontent.com/assets/18552272/25791066/6731c266-33db-11e7-8bcc-11294217cdb6.png)

https://codepen.io/anon/pen/MmOLQz?editors=1001

**Comment by randyaskin** [comment]
Inline CSS variables are not supported by the Polymer polyfill - https://github.com/Polymer/polymer/issues/2086

You should include it in a `<style is="custom-style">` block at the document level instead.

**Comment by amankumarshaw** [comment]
We tried using <style is="custom-style"> but still its not working.
Can you please provide any snippet for that.
![image](https://cloud.githubusercontent.com/assets/25499633/25851398/371a2786-34e3-11e7-90b3-94ae24aaaa3e.png)

**Comment by randyaskin** [comment]
Hmm, I'm not sure why `--px-data-table-border-color` is listed as a style variable, the one you actually want is `--px-data-table-cell-border-color`
