### ISSUE TITLE
Filter and sorting custom function not implemented and is present in the documentation

### ISSUE THREAD

**Issue by lmesta** [PredixDev/px-data-table#134]
Hi

I want to implement a custom function for sorting and filtering
Is present in the documentation but not in the px-data-table
Can you pls help me with this?

**Comment by randyaskin** [comment]
There are examples using the `filter-function-name` and `sort-function-name` properties of px-data-table-column in [this file](https://github.com/PredixDev/px-data-table/blob/master/demo.html#L141-L159) (see also line 91, 108 and 122). As stated in the API, we recommend namespacing them when attaching them to `window`.
