### ISSUE TITLE
On Page Refresh px-data-table does not save selected page size and selected page number in pagination

### ISSUE THREAD

**Issue by fsevak** [PredixDev/px-data-table#136]
Hi,

We have a use case where we change the page size from 10(default) to 50 for instance and also the selected page(page 2 for instance) and save the same , so after page refresh it should display same data with changed page number and page size without any further clicks.

For Example:
1. Select page size to be 20.
2. Select Page 2 from pagination.
3. Refresh/reload the page.

Actual : 
On page refresh/ reload page sizes goes back to 10 (default) and page 1(default) data is displayed.

Expected : 
On page refresh/ reload page size should be 20 and page number as 2.

**Comment by nonmetalhail** [comment]
The component cannot save state on a page refresh. Your app will have to handle that and save and apply user settings.
