### ISSUE TITLE
Aha Table Validation - Undefined exception

### ISSUE THREAD

**Issue by pagadalasrikanth** [PredixDev/px-data-table#139]
In the _refreshInternalData method of aha-table.html, 
` if(resetDataFlag){
              cellDataObj[key]._validation = {passedValidation: true};
            }else{
              cellDataObj[key]._validation = this._internalData[i].row[key]._validation;
            }`

If the data in a column is null, it throws an exception in the else block as we are calling "_validation" on an undefined.

Can we have a undefined check before calling the _validation,

**Comment by randyaskin** [comment]
Added in v3.0.3, let me know if this fixes your issue.
