### ISSUE TITLE
HTML fields fail in editCell method

### ISSUE THREAD

**Issue by charlestmichael** [PredixDev/px-data-table#140]
## Expected behavior and actual behavior:
Expected: You should be able to click on a cell in the px-data-table designated as type HTML and Editable and not have the table throw an exception

Actual: When click in on a cell in the px-data-table designated as type HTML and Editable, the table throws an error 'Type Error: Cannot read property 'innerText' of null'. This error happens in px-data-table-cell.html on line 306 in the editCell function:

if (this.cellEditable && this.cellType !=='dropdown' ) {

This line should be changed to include html types, like so:

if (this.cellEditable && (this.cellType !=='dropdown' && this.cellType !== 'html')) {

## Steps to reproduce the problem:
1. Create a table where there is at least one column in the table that is of type 'html'
2. Set the data value of the fields in this column to be an input type='text'
3. Go to your page in the browser
4. Click on one of the text boxes you defined in step 2. Click on it.
5. The application throws an error as described above.

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
px-data-table version 3.0.2
chrome 58.0.3029.110 (64-bit)

## Screenshots (_optional, but very helpful_):
![image](https://user-images.githubusercontent.com/11964020/27135200-efc398ee-50e5-11e7-9cef-88470ab74f5e.png)

## Code examples help us better understand the issue - follow the appropriate codepen for the component by going to https://predix-ui.com, finding the component in question, and clicking on the pencil icon under the demo.
        Once you've created your code example, you can save it under a new url.
        Please note that you should NOT use the same methods for production as the ones used in codepen - these methods are not production ready.

**Comment by randyaskin** [comment]
Fixed in v3.0.3. Thanks for logging / pull request.
