### ISSUE TITLE
Polymer 2 compatibility

### ISSUE THREAD

**Issue by samdz** [PredixDev/px-data-table#147]
Will there be a Polymer 2 version?

**Comment by randyaskin** [comment]
We will be moving to Polymer 2 for all of the Predix Design System components at some point this year, it was too much at once to completely redesign everything and migrate versions at the same time. :)  We are at 1.9 across the board so we can support 1.x/2.x hybrid components. We'll be doing some spikes in the next few weeks, now that the redesign is released, to evaluate our next steps for migration.
