### ISSUE TITLE
Px-pagination isn't working

### ISSUE THREAD

**Issue by baontvn** [PredixDev/px-data-table#152]
# Submit an Issue

Hi,

Thanks for helping us improve the Predix UI platform by submitting an issue.

Before you begin, please check the list of existing issues to avoid submitting a duplicate issue.

To help us solve this issue as fast as possible, please fill out the following sections:

When I change the value of Rows per page, the display value doesn't change the records on the table. 

## Expected behavior and actual behavior:
For example:
I have more than 20 records and I want to show 20 records per page. I change the value of Rows per page from 10 to 20 but the display values isn't changed. It still shows 10 records.
I have tried to fix this problem. If you add the attribute **notify: true** for property **pageSize** of the component Px-pagination. I worked as my expectation.

## Environment (_component version number, Browser (including version), operating system, hardware, etc_): 
My version is 4.0.6

## SceenShot:
![data-table-bug](https://user-images.githubusercontent.com/16508495/30419154-8e17ad98-995f-11e7-94f0-8776e6433a8b.PNG)

**Comment by randyaskin** [comment]
Good catch, and thanks for the fix.
