### ISSUE TITLE
Drop down in data-table throws a lot of errors

### ISSUE THREAD

**Issue by bote795** [PredixDev/px-data-table#156]
# Submit an Issue

## Expected behavior and actual behavior:
 * expected behavior:
   * select the option selected in drop-down.
 * actual behavior
   * selecting the option freezes and throws a lot of console errors and renders browser not workable for a few minutes

## Steps to reproduce the problem:
1. go to https://www.predix-ui.com/#/elements/data-table/px-data-table-column
2. select drop down option of data-table
3. click on a drop-down option
4. click again on a drop down option
 
## Environment (_component version number, Browser (including version), operating system, hardware, etc_):

chrome: Version 60.0.3112.113 (Official Build) (64-bit)
macOS Sierra
v 10.12.6

## Screenshots (_optional, but very helpful_):
![datatableerror](https://user-images.githubusercontent.com/5323384/30879456-48902cf6-a2b4-11e7-9a24-93498da793de.gif)

**Comment by mdwragg** [comment]
Hi, is this happening in your app or just our website?

**Comment by bote795** [comment]
This is happening in our app as well but found that it was happening on the website and figured would be best to report from your own website.

**Comment by davidrleonard** [comment]
We've pinned the regression down to the diff in f96d48510323100d6878f1a33d8b2ff81d04dd45 and are looking for a fix.

**Comment by randyaskin** [comment]
Merged #157 in v4.0.11
