### ISSUE TITLE
Show column chooser dropdown does not show initial visible columns as selected

### ISSUE THREAD

**Issue by davidrleonard** [PredixDev/px-data-table#158]
## Expected behavior

1. Open http://archive.predix-ui.com/#/components/px-data-table (pre-refresh demo)
2. Tap on "Complex" demo option
3. Tap the "Show/Hide Column" button at top right to open the dropdown
4. **All 3 items are checked because all 3 columns are visible.** ✅ 

![image](https://user-images.githubusercontent.com/6456757/30894230-6042a50c-a2f7-11e7-800a-de2406b5794e.png)

## Actual behavior

1. Open https://www.predix-ui.com/#/elements/data-table/px-data-table (post-refresh demo)
2. Tap on "Complex" demo option
3. Tap the "Show/Hide Column" button at top right to open the dropdown
4. **Only "First" is checked. All 3 items should be checked because all 3 columns are visible.** ❌ 
5. Tap "Last" to select it. Nothing happens, the "Last" column was already visible.
6. Tap "Last" to deselect it. The "Last" column is hidden. 
7. Tap "Last" again to select it. The "Last" column re-reappears.

![image](https://user-images.githubusercontent.com/6456757/30894240-75d67146-a2f7-11e7-8dce-0c990f57e190.png)

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):

* Chrome 62
* Mac OS X El Capitan

## Why tho? 🤔 

I think https://github.com/PredixDev/px-dropdown/issues/58 is the underlying issue.

**Comment by randyaskin** [comment]
Fixed in v4.0.13.
