### ISSUE TITLE
Support clear selected on multiple select table

### ISSUE THREAD

**Issue by nhantl1206** [PredixDev/px-data-table#163]
Please provide a method to clear the selection on the table. Currently there's no way to do that because the selectedRows is readonly.

**Comment by randyaskin** [comment]
The "select all" checkbox in the header row can be used to toggle Select All and Clear All.

**Comment by nhantl1206** [comment]
I mean in code, how can I deselect all in js?

**Comment by randyaskin** [comment]
Get a reference to the aha-table sub-component inside of px-data-table, then call `myAha._setAllRows(false)` on it.
