### ISSUE TITLE
Pagination behavior erratic with rows per page

### ISSUE THREAD

**Issue by randyaskin** [PredixDev/px-data-table#164]
# Submit an Issue
px-data-table showing all record instead of row-per-page count

## Steps to reproduce the problem:

- open data table with more than 10 record
- change row per page to 20
- click on page 2 from pagination
- All record displayed

Expected : it should show 20 rows
Result : it's displaying all records

## CodePen
https://codepen.io/anon/pen/boMqdQ?editors=1000

## Source
https://forum.predix.io/questions/28759/px-data-table-pagination-erratic-behaviour-with-ro.html

**Comment by arvindwanjari** [comment]
Hi Randy,

i did some debugging and found that issue with typecasting @ https://github.com/PredixDev/px-data-table/blob/master/aha-table.html#L749 


Fixed for my forked version .
to = fromPage + parseInt(this.pageSize, 10);

Thank you.

**Comment by randyaskin** [comment]
Thanks for the fix! Pushed in v4.0.15.
