### ISSUE TITLE
Pagination style broken in 5.x

### ISSUE THREAD

**Issue by jschlieber** [PredixDev/px-data-table#170]
Hi, was the style of the active page changed by intention?

## Expected behavior and actual behavior:

Expected style:
![px-data-table1](https://user-images.githubusercontent.com/11458212/31952097-153723f4-b8e0-11e7-8af6-cdde98950dc2.png)

Actual style (also see demo page): 
![px-data-table2](https://user-images.githubusercontent.com/11458212/31952148-36b85714-b8e0-11e7-8eb4-e99dc003e966.PNG)

## Steps to reproduce the problem:

Use latest version of px-data-table. Tested with and without shadow dom.

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
Google Chrome

**Comment by mdwragg** [comment]
@evandana, does this issue look familiar at all?

**Comment by randyaskin** [comment]
Fixed in v5.1.4.
