### ISSUE TITLE
when new column added filer for it is not present

### ISSUE THREAD

**Issue by ge-kosc** [PredixDev/px-data-table#171]
When column is added using column chooser, filter on that column is not present. 
px-data-table version is 5.0.1.

**Comment by randyaskin** [comment]
This is not the behavior I'm seeing on CodePen when I paste in a new column definition. As long as the table is `filterable` and the new column is also `filterable` it shows up fine. What method are you using to add a new column?

**Comment by randyaskin** [comment]
Fixed in v5.1.3.
