### ISSUE TITLE
[Help Wanted] Advanced Dropdown Options

### ISSUE THREAD

**Issue by ddubbindustries** [PredixDev/px-data-table#177]
(sorry didn't know how to set the issue label)

We're needing to do more with the dropdown option than currently available in the `px-data-table-column` attributes, among which are:

1. set `button-style="primary"`
2. enable `search-mode`
3. enable `multi`

We've tried injecting the component as html but that gets pretty stringy and loses the functionality of the table save events and other bindings. It'd be cool to be able to pass a full component into the body of the `<px-data-table-column>`. What do you suggest we do?

**Comment by mdwragg** [comment]
Dropdown and HTML type columns are the only support we have right now I'm afraid. We're working on a new data table right now but if there's any small tweak that would help, pull requests are always welcome. Thanks for your issue.
