### ISSUE TITLE
px-page-size-change-intent event is not triggered when page size is getting changed

### ISSUE THREAD

**Issue by haoruiqian** [PredixDev/px-data-table#179]
Code is here https://codepen.io/anon/pen/MOodyv?editors=1011

I added a listener that listens on event `px-page-size-change-intent`, when changed the page size by selecting different option after "Rows per page", the listener is not triggered, however, `px-page-change-intent` is triggered when clicking different page.

I already set `data-remote` in `px-data-table`, not sure if there's anything missed.

**Comment by randyaskin** [comment]
@evandana any chance you've seen this? Could just be that the `selected-changed` listener should be on the px-dropdown instead of the px-pagination component?

**Comment by evandana** [comment]
Sounds likely. I'll try to look at it this sprint once we release.

**Comment by LRagji** [comment]
Hey i have somewhat related problem, property 'pageSize' doesn't reflect the option selected from 'pageSizeOptions' property instead its always set to 10, i am not setting data-remote property is this supposed to work the way it is always stuck to 10?

**Comment by erikjswedberg** [comment]
Hello!  I am also hitting the issue precisely as @haoruiqian described.  Any update?

**Comment by randyaskin** [comment]
Merged PR in v5.1.13.
