### ISSUE TITLE
IE 11 Broken 5.0+, drop downs broken 4.13+

### ISSUE THREAD

**Issue by ntarora** [PredixDev/px-data-table#180]
Hi,

Encountered a problem with px-data-table in IE 11 with any version 5.0.0+. The table will not render, the only error I encounter is a syntax error in aha-table.js from the console.

When downgrading to version 4.0.15 the table would render, but the dropdowns then did not show up, had to downgrade to 4.0.12. Looks like 4.0.13 introduced px-dropdown 3.1.0 from 2.1.0.

We initially upgraded to fix a defect when editing the input field was smaller than the cell size so it would unnecessarily scroll too early. But this upgrade breaks our current usage. 

Testing was initially done on a Windows 7 IE11 machine then debugging was done on a VM for IE11 provided by MS.

Any guidance and feed back would be helpful.

**5.0.1 with no table render, we use it twice both instances don't show up, console error**
<img width="1678" alt="image" src="https://user-images.githubusercontent.com/7290966/32849700-d0c25ba6-c9e4-11e7-9c4a-fde7217aff24.png">

**4.0.15 No dropdown on new row**
<img width="1561" alt="image" src="https://user-images.githubusercontent.com/7290966/32849397-dcd0fc1e-c9e3-11e7-8b17-9723d5a95ff2.png">

**4.0.12**
<img width="1433" alt="image" src="https://user-images.githubusercontent.com/7290966/32848956-b3df2066-c9e2-11e7-90db-6dd99e932b43.png">

**Comment by mdwragg** [comment]
Hi,

Thanks for your issue! Sadly, I hate to do it, but I just tested the version on www.predix-ui.com in IE11 and it 'works on my machine'. Confirmed that this is latest 5.x version also...

**Comment by mdwragg** [comment]
Just to elaborate; "latest" IE 11 on Windows 10.

**Comment by ntarora** [comment]
I see could be a version mismatch of IE11 from Windows 10 to window 7.

I can’t even load predix-ui.com on the VM. Thanks for the feedback I know IE is a rabbit hole sometimes.

**Comment by mdwragg** [comment]
🤔 Weird. Just tried it on a Win 7 machine (a fine Dell vintage....) and all worked fine.

**Comment by ntarora** [comment]
Been playing around with it all day, even took the script off the predix-ui.com site and replaced it in our vulcanized file. Got a undefined babelHelper error when doing this...

So my guess is the way we are vulcanizing is causing an issue. Could be a comment stripping issue, since we do inline CSS and Scripts when we vulcanize. I'll close this and see if I can find any solution and update this issue.

**Comment by mdwragg** [comment]
Hmmm... that is strange. I just can't think of anything that would cause that.

Check out the polymer.json below for how we build the site using polymer CLI: https://github.com/predix-ui/predix-ui.github.io/blob/source/polymer.json

**Comment by mdwragg** [comment]
(that repo is the source for predix-ui.com BTW if there's anything else that helps in there)
