### ISSUE TITLE
can not use it with angular 5

### ISSUE THREAD

**Issue by jeado** [PredixDev/px-data-table#181]
## Expected behavior and actual behavior:

I`m trying to use  px-data-table with Angular 5. it worked if I only use <px-data-table> but with <px-data-table-column > id does not work what I expected. 

here is sample code of `app.component.html`

```html
<px-data-table table-data='[{"first":"Valentine","last":"Meyer","email":"valentinemeyer@scentric.com"},{"first":"Silva","last":"Alexander","email":"silvaalexander@gmail.com"},{"first":"Hopkins","last":"Wong","email":"hopkinswong@hotmail.com"},{"first":"Joe","last":"Sherman","email":"joejoe@yahoo.com"},{"first":"Jane","last":"Bartlett","email":"jane@scentric.com"}]'
  language="en" striped filterable sortable single-select show-column-chooser include-all-columns>
  <px-data-table-column name="first" placeholder="First Name" filterable sortable editable></px-data-table-column>
</px-data-table>
```
when I use this code in index.html it worked fine but in a angular component template it did not work. I assume that there is something wrong with <content>.

## Steps to reproduce the problem:

1. just try to use upper code in app.component.html

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):

angular 5, mac, chrome

## Screenshots (_optional, but very helpful_):
![image](https://user-images.githubusercontent.com/912457/32924891-53a22a44-cb82-11e7-9874-68822a1738f2.png)

**Comment by mdwragg** [comment]
Hello! Thanks for your issue.

I'm not an Angular developer, can you supply something stand-alone I can test this in? Glitch, codepen, jsbin etc.

Thanks.

**Comment by jeado** [comment]
@mdwragg

**Comment by jeado** [comment]
@mdwragg sure~

**Comment by jeado** [comment]
@mdwragg 

check out this 
https://embed.plnkr.co/IfGHhUUZ73AIyGdqo7uY/
and I found how it can be working.

```html
<base href="https://polygit.org/px-*+PredixDev+*/webcomponentsjs+v0.7.24/polymer+v1.9.1/components/">
  <link rel="import" href="px-theme/px-theme-styles.html" />
  <style is="custom-style" include="px-theme-styles"></style>
  <link href="polymer/polymer.html" rel="import">
  <link href="px-data-table/px-data-table.html" rel="import">
```
if you move upper code block below `<script type="text/javascript" src="https://run.plnkr.co/0pBlH7N1KIX28PRq/main.js"></script>` , it works well.

so i thinks it is about script loading...

**Comment by mdwragg** [comment]
Sweet! Glad it works. Please close this issue if you're up and running. Thanks!

**Comment by jeado** [comment]
@mdwragg but this workaround is not good enough to close this issue. for dev, angular-cli put script tags automatically the end of HTML body element so I cannot add `<link href="px-data-table/px-data-table.html" rel="import">` after angular main script...

**Comment by jeado** [comment]
and also because of adding  `<link href="px-data-table/px-data-table.html" rel="import">` this after angular main script, custom element initialized (upgraded) is done after  execution of angular stuff so it felts quite slow rendering experience.

**Comment by mdwragg** [comment]
Sooooo.... is the bug with us or Angular cli? I’m none-the-wiser how we would fix their bootstrapping issue?

**Comment by mdwragg** [comment]
Going to close this as the trail has gone cold and things seem to be working. Guessing this is an issue of bootstrapping loading order of NG and Polymer.

The fact that projects such as https://github.com/webpack-contrib/polymer-webpack-loader exist makes me confident that this is all working together. Not sure what extra assistance we can provide.
