### ISSUE TITLE
px-pagination breaks when pageSizeSelect undefined

### ISSUE THREAD

**Issue by elvinfucom** [PredixDev/px-data-table#182]
Line 412 at px-pagination

```
   var parentElem = this.$.pageSizeSelect,
        optionList = Polymer.dom(parentElem).querySelectorAll("option");
```
The pageSizeSelect sometimes doesn't exist. Then the querySelectorAll on option will return all option on page. This breaks parentElem.selectedIndex at line 418.

**Comment by mdwragg** [comment]
@evandana - on the face of it looks like some of the modifications you made for server-side pagination (feel free to tell me I'm wrong ;). Can you take a look?

@elvinfucom - as per the issue template, can we have a codepen/glitch/jsbin showing this error in isolation? Thanks, it helps us loads to debug the issue.

**Comment by elvinfucom** [comment]
I'm using the px-data-table under React, below is the trace stack when error happens.
And I have set the hidePaginationControl property correctly, just confused why setPageSize still be called.
Hope those info can help.

```

px-pagination.html:418 Uncaught TypeError: Cannot set property 'selectedIndex' of undefined
    at px-pagination.html:418
    at Array.forEach (<anonymous>)
    at HTMLElement._updatePageSize (px-pagination.html:415)
    at HTMLElement.setPageSize (px-pagination.html:214)
    at HTMLElement._setPageSize (aha-table.html:821)
    at HTMLElement._observerEffect (polymer.html:1613)
    at HTMLElement._effectEffects (polymer.html:1458)
    at HTMLElement._propertySetter (polymer.html:1442)
    at HTMLElement.__setProperty (polymer.html:1451)
    at HTMLElement._applyConfig (polymer.html:2064)
    at HTMLElement._afterClientsReady (polymer.html:2058)
    at HTMLElement._ready (polymer-mini.html:144)
    at HTMLElement._readyClients (polymer-mini.html:152)
    at HTMLElement._ready (polymer-mini.html:140)
    at HTMLElement._tryReady (polymer-mini.html:130)
    at HTMLElement._initFeatures (polymer.html:4135)
    at HTMLElement.__initialize (polymer-micro.html:235)
    at HTMLElement.createdCallback (polymer-micro.html:218)
    at window.Polymer (polymer-micro.html:63)
    at px-data-table.html:183
```

**Comment by randyaskin** [comment]
I don't think it's Evan's fault. It looks like when I cutover from the simple `<select>` menu to a `<px-dropdown>` instead, I didn't update this function to work accordingly. Looking into it.

**Comment by randyaskin** [comment]
Fixed in v5.1.8 by removing unnecessary code.

**Comment by shinxi** [comment]
@mdwragg @randyaskin We are mixing predix-ui into our React application, and React works best with Polymer v2 since Polymer v2 implements shadowDOM V1, can we ask a favor to have this fix to be merged at branch [polymer2.0-preview](https://github.com/PredixDev/px-data-table/tree/polymer2.0-preview) as well, that'll be very helpful.

**Comment by mdwragg** [comment]
Hi @shinxi,

Thanks for your comment.

In all likelihood that branch will never see the light of day and be released - there were way too many issues to resolve when migrating between 1.9 & 2.x. Given we're working on a reboot of our data table right now, it didn't make sense to invest the (significant) effort to complete the migration. You can take a sneak peak of the new table here: https://github.com/vaadin/px-data-grid

This will be based on the very successful Vaadin Grid and be Polymer 2 only - please take this only as a preview of what is to come, there's significant engineering effort going on with this new grid and things will change significantly before release next month ;)

**Comment by elvinfucom** [comment]
Hi, @mdwragg 
Thanks for the explanation! Looking forward to the new data grid, it looks great.

However I still argue to apply the fixing that @randyaskin did to the branch of polymer2.0-preview. Firstly, those are dead legacy code due to replacing html select with px-dropdown. 
Secondly, those code can break the data table to work. 
Finally, the fixing that @randyaskin did looks straight forward, I'm not sure how it needs "to invest the (significant) effort to complete the migration". 
How do you think?

Thanks.

**Comment by mdwragg** [comment]
I don't intend to make any further changes to an (abandoned) development branch. It is pretty dangerous to base on serious development on such a thing also!

Given that it appears people are using it, I won't delete it but I'd encourage you to take a fork of it at least to stop inadvertent things happening to it.

**Comment by elvinfucom** [comment]
I see, thanks for the reply.
Looking forward to the new data grid.
