### ISSUE TITLE
Demo page is broken

### ISSUE THREAD

**Issue by limonte** [PredixDev/px-data-table#191]
https://www.predix-ui.com/#/elements/data-table/px-data-table

There's no code example and live demo:

![](https://i.imgur.com/NerstdJ.png)

Chorme/Linux, Firefox/Linux. No errors in console.

**Comment by randyaskin** [comment]
The px-data-table is the only component we will not be upgrading to Polymer 1.x/2.x hybrid, all of the other components have been upgraded and the predix-ui.com site was switched to Polymer 2 at the end of the year (can only run one version of Polymer at a time with the way the site is architected). You can still refer to the documentation for data-table at https://www.predix-ui.com/px-data-table/px-data-table/ until the table is replaced completely by the Polymer 2 Vaadin-based px-data-grid in mid-January.
