### ISSUE TITLE
px-data-table-highlight incorrectly highlights the same row in all the pages of px-data-table

### ISSUE THREAD

**Issue by AkshayMehta90** [PredixDev/px-data-table#194]
# Submit an Issue

Expected behavior: px-data-table-highlight should only highlight the row that is meeting the specified criteria.

Actual behavior: It highlights the same row number on every page of the px-data-table even when they do not meet the criteria.

Eg: If row# 2 on 1st page is meeting the highlight criteria, it gets highlighted as expected. But all the subsequent pages (2,3...10) etc, also has the row number 2 highlighted even though they do not meet the criteria. Also if I go to the last page, and say it does not have row 2(only one row), and then navigate backwards, than all the incorrectly highlighted rows disappear this time. Looks like it is persisting the highlight behavior for all pages.

## Steps to reproduce the problem: 
1. Have data that can span for 3 4 pages of the data table.
2. Make a unique row in the 1st page to meet the highlight criteria so that it gets highlighted.
3. Navigate using the pagination scroll to next pages, and you should be able to see the same highlighted in all the pages.

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
"px-data-table": "5.1.5"
Browser: Chrome Version 63.0.3239.132 (Official Build) (32-bit)
Operating system: Windows 10

## Screenshots (_optional, but very helpful_):
![last-page-no-highlight](https://user-images.githubusercontent.com/35950626/35553392-c323b58e-05bd-11e8-822a-d9677cd3828e.jpg)
![unexpected-highlight](https://user-images.githubusercontent.com/35950626/35553393-c36b83b4-05bd-11e8-818e-f315e644a7c1.jpg)
![expected-highlight](https://user-images.githubusercontent.com/35950626/35553394-c3b1469c-05bd-11e8-926e-773d7afdd360.jpg)
![highlight-row-gone](https://user-images.githubusercontent.com/35950626/35553395-c41d4a9a-05bd-11e8-8e44-bc5014219200.jpg)

**Comment by AkshayMehta90** [comment]
## Code examples help us better understand the issue:

## dataTable-error-highlight.html
<script>
    PxHighlight = {
        hasError: function hasError(value, row, column) {
            console.log('in highlight');
            if (row.error.value === -1) {
                console.log('in if condition with value: ' + row.error.value + ' and tag : ' + row.name.value);
                return true;
            }
        }
    };
</script>


## Html code:
      <px-data-table-column name='vwTagName' type="html" label='[[localize("TAG_name")]]' filterable>
        <px-data-table-highlight highlight-type="row" highlight-value="high" highlight-method="hasError" import="/public/elements/dataTable-error-highlight.html">
        </px-data-table-highlight>
      </px-data-table-column>


Also on filtering, the highlight still remains on row number 2 even when highlighted row is not part of filtering.

**Comment by randyaskin** [comment]
This is not the behavior I see in the default component (using demo.html from the repo), the component is re-setting highlight on filter/page change. Are you by any chance using the `data-remote` paradigm?

Unfortunately, as you pointed out, it's very hard to isolate this particular behavior and it doesn't work in CodePen because of the external file dependency.

**Comment by AkshayMehta90** [comment]
Thanks for your quick response Randy. And no we are not using the data-remote paradigm.
We have though, noticed one thing. The px-data-table-cells that are holding the data on every page, they all have the same Id. I guess this is creating the issue. Can we have all the cells generate a unique id on every page? Am attaching a screenshot depicting the same. Cells on page 1 and 2 have same id.

 ## For Reference, below is the code snippet for px-data-table:
<px-data-table id="1" table-cells="true" table-data="{{data}}" language="{{language}}" filterable resources="{{resources}}"></px-data-table>

![cells-same-id](https://user-images.githubusercontent.com/35950626/35606736-ada2a15c-0676-11e8-8bb6-43796586b676.jpg)

**Comment by AkshayMehta90** [comment]
Hi, Issue has been resolved. Problem was we were returning only 'true' and no 'false' from the highlight method.
Thanks for your Support.

Regards,
Akshay Mehta

**Comment by randyaskin** [comment]
Glad you were able to figure it out. 👍
