### ISSUE TITLE
enhancement needed

### ISSUE THREAD

**Issue by nraafee** [PredixDev/px-data-table#195]
Hello Team,

without header we couldn't able to display all the columns. Sometimes we need to display some 4 columns alone without header. So help us out in fixing this issue.

When mouse over the row has to change to other color and when user mouse out on particular row then it should be in default color.

Please let me know your comments.
Regards,
Raafee N

**Comment by randyaskin** [comment]
For blank headers, use the `label` property and pass in a blank space. To change the hover color of your rows, use the provided CSS variable `--px-data-table-row-background-color--hover`. This CodePen shows both in action: https://codepen.io/randyaskin/pen/YeLJPg?editors=1000
