### ISSUE TITLE
Polymer 2

### ISSUE THREAD

**Issue by 6palace** [PredixDev/px-data-table#197]
## Expected behavior and actual behavior:

expect polymer 2 dependency, gets polymer 1.7

## Steps to reproduce the problem:

`bower install https://github.com/PredixDev/px-data-table.git --save`

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):

all

**Comment by 6palace** [comment]
https://github.com/PredixDev/px-data-table/issues/147
It is now 2018. Has there been any progress on this? We are using the Predix UI, and other components are supporting Polymer 2.

**Comment by mdwragg** [comment]
We're launching a new data-grid this week based on the vaadin grid. Keep your eyes peeled for px-data-grid on predix-ui.com.

**Comment by mdwragg** [comment]
(you can take a look at it here: https://github.com/vaadin/px-data-grid)

**Comment by nonmetalhail** [comment]
Probably should be noted that this week is a BETA launch.

**Comment by 6palace** [comment]
cool, thanks for this.
