### ISSUE TITLE
Support referencing nested properties in px-data-table-column

### ISSUE THREAD

**Issue by rishabhtulsian** [PredixDev/px-data-table#23]
If the data for px-data-table is an array of objects each of which look like this
`{ a: 'prop a', b: { c: 'nested prop c' } }`

px-data-table-column should support referencing the nested property in a column

```
<px-data-table table-data="{{data}}">
  <px-data-table-column name="a"></px-data-table-column>
  <px-data-table-column name="b.c"></px-data-table-column>
</px-data-table>

```

One way to implement this is by using lodash. Look at this commit for the changes
https://github.com/rishabhtulsian/px-data-table/commit/2cc119ab3ad5927f37deac0a400e8c0f17f74030

**Comment by nonmetalhail** [comment]
@carlosfhernandez This is a feature request. Can you please prioritize this?
