### ISSUE TITLE
Data in table is not updated when dataObject is set to empty array

### ISSUE THREAD

**Issue by kwge** [PredixDev/px-data-table#30]
This used to work on v1.8.2, but since updating to v1.9.0, the data in table will not update to reflect the changes set in dataObject.

Example:  Initially array is set to 500 objects. Then with external triggered, we change the array to emtyo array.  The data table still showing the 500 objects.

**Comment by mdwragg** [comment]
@kwge - thanks for reporting. I've got a fix, just testing it now. Sorry for the regression, it was some over-zealous error checking.

Should be a fix available today.

**Comment by mdwragg** [comment]
Fixed in 5cebd00
