### ISSUE TITLE
Fix for the Warning Message "couldn`t decode Array as JSON"

### ISSUE THREAD

**Issue by ram4rishi** [PredixDev/px-data-table#35]
polymer-micro.html:624 Polymer::Attributes: couldn`t decode Array as JSON

**Comment by arcpato** [comment]
This error always appears when adding px data table to our application.

**Comment by mdwragg** [comment]
Closing as this is an angular interop issue (and is only a warning). Following patterns such as those proposed here: https://github.com/robdodson/polymer-framework-interop will avoid this warning message.
