### ISSUE TITLE
px-row-click should fire on selection of row

### ISSUE THREAD

**Issue by mdwragg** [PredixDev/px-data-table#38]
px-row-click should fire on selection of row - currently it only fires when table is selectable and user clicks on the checkbox 'select' column.

**Comment by dwarhya** [comment]
Hi,  is there any timeline on this enhancement please, as I need this to work

Thank-you

**Comment by mdwragg** [comment]
Sadly no plan right now. We ❤️ Pull requests though! 😊

**Comment by dwarhya** [comment]
Inside of the save event that bubbles up from controls embedded in the px-data-table, you can get the row using e.model.internalRow.row.  This just needs exposed as a property

**Comment by DipenV** [comment]
We also have the same use case where we need to support row click but do not require selectable column to be displayed.
Can it be planned and considered as a part of new enhancement ?

**Comment by mdwragg** [comment]
@DipenV - please help us build it if you need it urgently! :-)

**Comment by randyaskin** [comment]
Fixed in 2.0.0 - now when a user clicks on a non-editable and non-dropdown cell, the row-click event is also fired and the select/deselect occurs.
