### ISSUE TITLE
404 on Typography

### ISSUE THREAD

**Issue by jonniespratley** [PredixDev/px-data-table#41]
The .css file is located a level down in the directory, the component expects the fonts to be up 1 directory.
The solution is a style module, since the module lives top level the requests will become 200.

Ill send a pull request soon.

**Comment by mdwragg** [comment]
Nice - thanks @jonniespratley!

**Comment by mdwragg** [comment]
Fixed by a5c789bf9b665909d1f0ccd29283e632e75bff8e
