### ISSUE TITLE
Need options for cross column validation

### ISSUE THREAD

**Issue by spachalla** [PredixDev/px-data-table#42]
Hi,

I had a brief discussion w/Martin Wragg regarding this requirement for px-data-table.
Description is as given below 

Say I have column A and column B. 
Column A has some values, column B has dropdown list of data types. Based on the data type selected say string or numeric I need to validate data in column A and make user edit column A to match the data type. Currently it allows same column edit and validation, can we do cross column validation also?
Thanks in advance.

**Comment by mdwragg** [comment]
Closing cause age and that we wont get near this. We're also working on a new data table as we speak.
