### ISSUE TITLE
how to reuse one px-data-table for multiple db tables.

### ISSUE THREAD

**Issue by harithadikamalla** [PredixDev/px-data-table#45]
Hi I have a issue with px-data-table

i have 2  db tables with different columns.
using rest service getting data from first db table and passed into the px-data-table.
px-data-table displaying columns and data perfectly.

if i make a new request which is getting data from second db table and passed into the px-data-table. 
here px-data-table not displaying second db column names. still it was showing first db table column names.

how to reuse one px-data-table for multiple db tables.

**Comment by mdwragg** [comment]
Hi, thanks for your question. I believe this was fixed by #44
