### ISSUE TITLE
demo does not work at : http://predixdev.github.io/predix-ui/?show=px-data-table&type=component

### ISSUE THREAD

**Issue by joeblew99** [PredixDev/px-data-table#46]
on chrome stable on OSX.

get blank screen, when i click Demo in top right.

**Comment by mdwragg** [comment]
Hi, stable on chrome but broken on which browser/OS? Thanks.

**Comment by randyaskin** [comment]
@mdwragg I think it was all one thought... demo doesn't work on chrome (browser) stable (version) OSX (operating system). I see the same thing, and also for px-chart as well. For some reason the old demos don't work in the iframe of the new demo site and we haven't released the new demo for data-table yet.

@joeblew99 in the meantime you can still access the data-table demo here, it just isn't working inside the hierarchical navigation right now: http://predixdev.github.io/px-data-table/px-data-table/index.html

**Comment by randyaskin** [comment]
New demo for data-table has been released.

**Comment by joeblew99** [comment]
@randyaskin thanks. Its looking really great BTW.
