### ISSUE TITLE
How to split label (header name) of px-data-table-column

### ISSUE THREAD

**Issue by contactrajiv08** [PredixDev/px-data-table#48]
Hi,

I need to split the header name of a column in two rows because it is to long to show as a column header, i tried `</br>` but it is not working and showing `</br>` along with the header name.

Code example: `<px-data-table-column type="string" name="strone" label="Strategic ERP </br> The Rule Lives On" ></px-data-table-column>`

Please suggest a solution for this.

Thank You,
Rajiv

**Comment by randyaskin** [comment]
The tag is `<br/>`, but you can't pass HTML through a string in that way, it will always be interpreted literally by our code. In v1.12.7 I've added wrapping on column headers, but we would still probably advise against long column headers that could cause other display issues.

**Comment by contactrajiv08** [comment]
Hi Randy,

Thanks for your quick response. Can you please paste here a code example to wrap the header text.

Thank You,
Rajiv K

**Comment by randyaskin** [comment]
No code required from your side. The header will wrap if the name/label is longer than the space available.

**Comment by PradeepaSoundar** [comment]
@randyaskin is there any possibilities to align column headers. By default headers will be left aligned, how can i align it center?

I have one more question:

I know "max-column-character-width" attribute will be used set column max length. But how can i set column width? If text exceed cell width, how can i show tooltip onhover?
Note :

**Comment by randyaskin** [comment]
Column headers are always left aligned, we don't expose a way for you to center them today. And we don't currently have a way to specify column width either - they are sized automatically.

**Comment by yadavricha1288** [comment]
Hi,
    I am looking for a solution to give column names with space in px-data table ex-Company Name, Company Id etc. 

Really appreciate if any suggestion for the same!
Thank You!
Richa
