### ISSUE TITLE
Add support for custom highlight colors

### ISSUE THREAD

**Issue by leahecole** [PredixDev/px-data-table#49]
# Submit an Issue

Hi,

Thanks for helping us improve the Predix UI platform by submitting an issue.

Before you begin, please check the list of existing issues to avoid submitting a duplicate issue.

To help us solve this issue as fast as possible, please fill out the following sections:
## Expected behavior and actual behavior:

When I type in the code below, which is directly copied from the px-data-table-highlight.html file, then when the cell fits the condition set forth by my highlight functions, my cell should be highlighted to the color I specify. 
`<px-data-table-highlight highlight-color="rgb(67,100,221,0.25)" type="row" method="isLongString" import="px-data-table-highlight-example.html"></px-data-table-highlight>`

Actual behavior: This doesn't happen. There is a "calculateHighlightColor" function in px-data-table-highlight that is never used, which I suspect may have something to do with the issue.
## Steps to reproduce the problem:

Make a px data table, add some columns, add highlighting to one of the columns, and add highlightColor instead of highlightValue. 
## Code examples help us better understand the issue - follow the [CodePen](http://codepen.io/mdwragg/pen/LNwmpB) or [jsfiddle](https://jsfiddle.net/Lqmcwhw0/3/), templates, which both use polygit, to help explain the issue.

^^These templates are for px-rangepicker. :( 

Here is our code. Note the three highlights - the top one, which has highlight-color, does not work as expected. When I use highlight-value for all of these, it works swimmingly with my specified highlight functions. 

```
<px-data-table id="kitManagerTable" show-column-chooser enable-column-resize enable-column-reorder hide-pagination-control table-data="{{data}}">
        <px-data-table-column name="kit-asset-uuid" sortable></px-data-table-column>
        <px-data-table-column name="display-name" sortable></px-data-table-column>
        <px-data-table-column name="status" sortable>
        <px-data-table-highlight highlight-type="cell" highlight-color="rgb(255,0,0,0.25)" highlight-method="isRunning" import="/src/kit-manager-highlight.html"></px-data-table-highlight>
          <px-data-table-highlight highlight-type="cell" highlight-value="medium" highlight-method="isStartingOrUpdating" import="/src/kit-manager-highlight.html"></px-data-table-highlight>
          <px-data-table-highlight highlight-type="cell" highlight-value="high" highlight-method="isStoppedOrFailing" import="/src/kit-manager-highlight.html"></px-data-table-highlight>
        </px-data-table-column>
        <px-data-table-column name="last-updated" sortable></px-data-table-column>
      </px-data-table>
```

**Comment by ashleydf** [comment]
Has this bug been fixed yet?

**Comment by ashleydf** [comment]
I am still seeing this bug. Even when using the Predix-Seed and altering the data-table-view. The  highlight-color attribute does not work. 

Here is the code altered 
 
![screen shot 2016-12-01 at 8 45 32 am](https://cloud.githubusercontent.com/assets/14944323/20802982/92bcac4e-b7a2-11e6-9497-bb14c8553798.png)

Which produces this in the broswer: (the highlighted rows should be red). 
![screen shot 2016-12-01 at 8 46 10 am](https://cloud.githubusercontent.com/assets/14944323/20803013/b15361fc-b7a2-11e6-8ad4-d1d504a3a1ac.png)

When inspecting the row color I see this class has been added: 
class="style-scope aha-table td aha-units-td x-scope px-data-table-cell-0 cell--value__highlight--color__low"

Am I missing something?
