### ISSUE TITLE
Any upcoming support for handling paging/sorting/filtering by connecting it to a REST API service?

### ISSUE THREAD

**Issue by binson1989** [PredixDev/px-data-table#50]
Currently paging/sorting/filtering works on the local data set.
Is there any existing feature which allows us to use a REST API service instead that will return paged/sorted/filtered data? Or any upcoming plans to implement this in the near future?

**Comment by mdwragg** [comment]
Hi,

No immediate plans to add this. You could implement this in your application logic, `px-data-table` will simply react according to the data that your application passes to it. Thanks for your question!
