### ISSUE TITLE
px-data-table Taking long time to load in IE11

### ISSUE THREAD

**Issue by Raghava-47** [PredixDev/px-data-table#52]
loading px-data-table in IE is taking long time and till it get loaded all other features on the same page is blocking. 

for every action on px-data-table(like pagination,drop down selection) is also blocking other features on the same page.

we don't see this behavior on chrome.

in console debugger, it is not providing any information to trouble shoot.
 
is there any thing in IE needs to be configure or enable?

**Comment by mdwragg** [comment]
Hi,

Can you resubmit the issue adhering to the template and providing us with the information requested? Thanks.

Martin.
