### ISSUE TITLE
px-data-table taking long time to load in IE11

### ISSUE THREAD

**Issue by Raghava-47** [PredixDev/px-data-table#53]
loading px-data-table in IE is taking long time and till it get loaded all other features on the same page is blocking. 

for every action on px-data-table(like pagination,drop down selection) is also blocking other features on the same page.

we don't see this behavior on chrome.

in console debugger, it is not providing any information to trouble shoot.
 
is there any thing in IE needs to be configure or enable?

## Steps to reproduce the problem: 
1.	Copy the attached file in any folder.
2.	Go to that folder from command line.
3.	Run bower install https://github.com/PredixDev/px-data-table.git --save
4.	Run npm install polyserve -g
5.	Run the app polyserve
6.	copy the url printed on the console <URL>/datatable-test.html

## Code examples help us better understand the issue - Attached the html file what we are using for testing.

[datatable-test.zip](https://github.com/PredixDev/px-data-table/files/470508/datatable-test.zip)
[IE vs Chrome.pptx](https://github.com/PredixDev/px-data-table/files/470509/IE.vs.Chrome.pptx)

**Comment by mdwragg** [comment]
Hi,

Are you vulcanising your assets (https://github.com/Polymer/vulcanize)? This will dramatically speed up loading of any component.

**Comment by gpraveensingh** [comment]
Hi Martin,
This is the comment from one of our engineer who tried vulcanization:
"I tried the vulcanize tool, but it is making the html useless on IE. I was getting errors like cannot register the element (looks like DOM is not created while some javascript is trying to load)"

Thanks,
Praveen Singh

**Comment by mdwragg** [comment]
What version of Polymer are you using?

**Comment by gpraveensingh** [comment]
Polymer version: v1.6.0

**Comment by mdwragg** [comment]
Give 1.4.x a go, I noticed an issue in > 1.4 that I'm trying to track down.

**Comment by gpraveensingh** [comment]
Same behaviour with 1.4.0 as well.

**Comment by mdwragg** [comment]
You're absolutely sure you resolved for 1.4? When I try the example you uploaded here with Polymer 1.4.0 the difference is dramatic. In the console you can type

Polymer.version

To check the version that is running.

**Comment by mdwragg** [comment]
Just recreated this in your example on IE11 on Windows 10:

Load and render time:
With Polymer 1.4.0 - 2.44 seconds
With Polymer 1.6.1 - 12.49 seconds

**Comment by gpraveensingh** [comment]
Hi Martin,
Thanks a lot for your help & support. For now we have moved to angular table as we were in tight schedule. Please close the issue.

Thanks,
Praveen Singh

**Comment by mdwragg** [comment]
Reopening as it still needs fixing in Polymer 1.4+

**Comment by mdwragg** [comment]
I've reported a defect in the Polymer repo, they are working on it now:

https://github.com/Polymer/polymer/issues/3965

**Comment by mdwragg** [comment]
Fixed by: https://github.com/Polymer/polymer/releases/tag/v1.7.0

You can test the fix here:
http://predixdev.github.io/predix-ui/?show=px-data-table&type=component

**Comment by swetapatil** [comment]
I am facing performance issues in IE 11. I am using Polymer 1.7 and still performance is bad. I tried using Polymer 1.4 but no luck. When number of records selected per page are less, It works fine but when I select 100 records per page then performance drops dramatically. IE takes lot of time to respond.
