### ISSUE TITLE
Embedded controls compressed

### ISSUE THREAD

**Issue by dwarhya** [PredixDev/px-data-table#56]
I have a px-data-table with dropdown lists in two columns.  When I select the dropdown list in the top row, it is squished
<img width="916" alt="screen shot 2016-09-23 at 09 27 23" src="https://cloud.githubusercontent.com/assets/19690117/18779278/42d57f70-8170-11e6-98d9-feb42c642972.png">

Can you please fix the control so the popup window goes above or below the control depending on the position of the control

**Comment by randyaskin** [comment]
@dwarhya what you've requested is actually exactly what px-dropdown is already coded to do. It's designed to automatically drop down or up depending on where there is more available room within its parent container (in this case, the data table). You can see it in action when there are more than two rows [like this](http://codepen.io/randyaskin/pen/WGkbEB?editors=1000) - the first row drops down, the second and third rows drop up instead. The issue with a really small table with only two rows is that there isn't really anywhere for it to go, so it adds that scrollbar.

I agree that in this particular situation, it might make more sense for it to drop down and cover up the pagination controls or whatever other content is below it on the page, but @runn-vermel based the px-dropdown behavior on the size of the parent container to support as many use cases as possible.

**Comment by dwarhya** [comment]
@randyaskin, Fair enough.
