### ISSUE TITLE
page-size do not impact the number of row in the table

### ISSUE THREAD

**Issue by arnaudLC35** [PredixDev/px-data-table#58]
Hi,

While using the code:
`
 <px-data-table page-size="50" table-data="{{data}}"></px-data-table>
`

The number of the number of row in a page remains 10 instead of being modified to 50.

Except that the table is working as expected:
- Other options (stripped, filterable...) are working correctly.
- The file is correctly loaded over multiple pages (30 pages)
- when changing manually "Rows per page" it is correctly updated and display 50/100... rows per page.

Using px-data-page: v1.13.3

**Comment by mdwragg** [comment]
Oh no! @fjacquel kindly submitted that PR. @fjacquel, have you seen this issue in your app?

**Comment by fjacquel** [comment]
Hi Arnaud & Martin, 
The pull request was not included in v1.13.3. ¨
I have tested the integration with v1.14.0 and it works. So Arnaud you can upgrade to this version.

**Comment by arnaudLC35** [comment]
Hi fjacquel & Martin,

Indeed the latest version is working perfectly. I am using "#latest" in bower to avoid this type of issue but it seems it was conflicting with one of the element I do not used.

Thanks for your help and support.

**Comment by mdwragg** [comment]
Oops... you are quite right @fjacquel - I was having version blindness. Thank you for confirming this and thanks again for the great PR :)
