### ISSUE TITLE
Getting error when checking the selected checkbox

### ISSUE THREAD

**Issue by contactrajiv08** [PredixDev/px-data-table#61]
Hi,

I am using px-data-table component to show some records and each row of data-table contains a switch. I am able to get  checked status for all the switches available on the current page in pagination, but not able to get checked status of switches available on other pages in pagination. 

Below is the angular code i am using: 
`$scope.alldata` is a JSON object which is rendered to px-data-table.

`for(var l=0; l<$scope.alldata.length;l++){
                   var chkdstat = document.getElementById($scope.alldata[l].id).checked;
                  if(chkdstat){
                  allids += $scope.alldata[l].id+',';
                }
              }`  

When this loop reaches to the next page i get this error `Uncaught TypeError: Cannot set property 'code' of null`.

Please suggest, how to get checked status of switches of other pages in pagination.
Thanks,
Rajiv

**Comment by mdwragg** [comment]
Hi,

I'm not following the example unfortunately... Can you elaborate on your example please? That code appears to be all your logic/angular and nothing to do with px-data-table.

Can you create a codepen/create an example on github for us to recreate the issue?

If you click on the pencil icon here (http://predixdev.github.io/predix-ui/?show=px-data-table&type=component) you will get a minimal codepen to start from.

Thanks.

**Comment by contactrajiv08** [comment]
Thanks! for your quick response. I am not sure if my code would run in codepen because i am using predix-seed app as template. They have there own way to run angular code.

![img](https://cloud.githubusercontent.com/assets/7464756/19193840/55433152-8cc9-11e6-9b8d-77b752e7822d.png)

Please see attached screenshot of data-table with pagination and a Run button below it. And on click of Run button i am calling an angular function where i am trying to get the checked status of switches. 

The problem here is, when i select some switches from a page and some switches from other pages of data-table and then i click on Run button. Then in my angular code i can get the checked status of only those switches from which page i have clicked the Run button not for the switches on other pages.

Let me know if this clarifies you my issue.

Thanks,
Rajiv

**Comment by mdwragg** [comment]
Hi,

Sorry, I'm still not really following... Can you create a demo page hosted on github to show your issue? For instance, I reported a defect in Polymer and create a repo to show the issue:

https://github.com/mdwragg/polymer16-data-table
And hosted on github pages: https://mdwragg.github.io/polymer16-data-table/

That said, I _think_ it looks like you are querying the ID of elements that may not actually exist on the page? If there are 10 rows on the page in the data table only 10 of those toggle switches *actually* exist in the DOM, as the model (data) changes underneath the table the dom is manipulated to match the state of the model (and your logic that controls it). If you have 500 'rows' of data in your table still only 10 rows exist on the page/in the DOM.

**Comment by contactrajiv08** [comment]
Yes, i am querying the ID of the switch element, sorry i forgot to mention it in my query. So the actual problem is DOM and If there are 10 rows on the page in the data table then only 10 of those toggle switches will exist in DOM and only these 10 items can be queried. Got the issue! But if i want to get all  the Switches (like, if there are 500 rows) in DOM, then what i need to do. I have to query all the IDs of switches.

Please suggest.

Thanks,
Rajiv

**Comment by randyaskin** [comment]
If I understand your comment correctly, you would have to set the page size to 500 rows so that all would be displayed at the same time, which would probably cause a big performance hit.

**Comment by mdwragg** [comment]
Closed as the trail seems to have gone cold...
