### ISSUE TITLE
Sorting not showing the up/down arrow icon

### ISSUE THREAD

**Issue by contactrajiv08** [PredixDev/px-data-table#64]
Hi,

I have made sortable='true' for some columns, and when i click on header label to sort the column it is not showing the up/down arrow icon. See below screenshot for example of icon.

![sort](https://cloud.githubusercontent.com/assets/7464756/19688928/41e7722a-9ae9-11e6-8533-ec59a075ea75.png)

 Also is it possible to show a label 'Sort' as tooltip on hover over the column header which is configured for sorting.

Thanks,
Rajiv

**Comment by randyaskin** [comment]
Are you coding `sortable=true` in the HTML definition of the px-data-table-column directly, or trying to dynamically add it later? As it says on the [demo page](http://predixdev.github.io/predix-ui/?type=component&show=px-data-table) for px-data-table-column (click the link under "Children Components") a few of the column properties are not set up for dynamic switching, they have to be set upfront or else there is some weird behavior. We have a backlog item to make them all dynamic.

I believe another team has requested some kind of affordance to indicate sorting is possible (showing both an up and down arrow in black, for instance) which is also in our backlog and would accomplish the same thing as your suggested tooltip solution.

**Comment by mdwragg** [comment]
I've fixed this in the latest release 204beb93ddcf8196c6c1e5dc7eca7e1d43161967
