### ISSUE TITLE
Allowing lazy loading with infinite scroll

### ISSUE THREAD

**Issue by benmak11** [PredixDev/px-data-table#66]
Hi,

This is not really an issue but more of a feature request. Is it possible to have infinite scroll with a restricted pageSize view of 25 items? I know that out of the box, px-data-table does support lazy loading via paginating the data set (and restricting the displayed set of data to the page size that you stipulate). px-data-table does not support infinite scroll, which is what I am trying to achieve. More details on this is [here](http://forum.predix.io/questions/13986/restricting-px-data-table-to-show-only-25-items-an.html#answer-14038).

**Comment by mdwragg** [comment]
Hi,

Thanks for your feature request! We don't have plans to build this feature right now. Can you help us build it? We love pull requests!

Thanks!

**Comment by benmak11** [comment]
Okay @mdwragg! I will do that. Once the pull request is submitted and accepted, I will close this issue.

Thanks

**Comment by mdwragg** [comment]
Awesome! @benmak11 I can't wait to see it :) 💯

**Comment by benmak11** [comment]
@mdwragg could I get access to this repo? I can't create a branch cause I run into this in the command line:
<img width="823" alt="screen shot 2016-10-27 at 11 54 49 am" src="https://cloud.githubusercontent.com/assets/6559240/19774789/4061d3e2-9c3c-11e6-9329-a61a1ff008af.png">

**Comment by mdwragg** [comment]
Hi Ben, you will make your changes in a fork of this repo. Fork the repo to your personal GitHub account, make your changes then create a PR pointing to your changes (there are tons of guides on the internet on how to do this). Let us know if you get stuck!

**Comment by jouni** [comment]
Hi!

I noticed this feature request and followed the discussion at http://forum.predix.io/answers/14038/view.html, where Baynham Makusha linked to vaadin-grid as an alternative to use.

I started to wonder if you would be interested in bringing vaadin-grid into Predix UI? We’re currently actively working on vaadin-grid 2.0 (check the [latest preview demos](https://cdn.vaadin.com/vaadin-core-elements/preview/vaadin-grid/demo/)), and we would be very interested in hearing why you would not consider it and would rather write your own data table element (missing features, unwanted features, political reasons or something else).

As a sidenote, the Predix UI library and design system are a real inspiration for us at Vaadin, so keep up the good work!

**Comment by randyaskin** [comment]
Will be introduced with https://github.com/PredixDev/px-data-table/pull/126

**Comment by benmak11** [comment]
@randyaskin has this [PR](https://github.com/PredixDev/px-data-table/pull/126) been merged into master? I would like to take a look at the final solution

**Comment by randyaskin** [comment]
Nope, if you click on the link you'll see the status, latest commits, and conversation with Evan though. Maybe you can help him with his I.E. woes.

**Comment by mdwragg** [comment]
Lazy loading now available. Infinite scroll will be available in the new data table (coming soon). Closing this issue.
