### ISSUE TITLE
px-data-table loading time slow performance

### ISSUE THREAD

**Issue by arcpato** [PredixDev/px-data-table#69]
Hi, 

The px-data-table component load time is very slow. It currently takes ~5 seconds to load, after the data has come back from the backend. We are experiencing this delay in a table of 250 items.

The expectation is to load within ~1-2 seconds after the data has returned from the back-end.

Thank you.

**Comment by benoitjchevalier** [comment]
Hey,

any chance you can provide us the data, or even better provide a jsfiddle/codepen (using this as a starter for example: http://codepen.io/FrenchBen/pen/gwJVPy?&editors=1001) demonstrating the issue? 5s does seem like a long time, our demos are a lot quicker

Also which browser are we talking about?

**Comment by arcpato** [comment]
I'll ask my team to fetch the metrics. Thanks!

**Comment by mdwragg** [comment]
250 sounds like a lot... does that even fit on a page? I'd suggest restricting the page size of the table for immediate performance relief.

**Comment by mdwragg** [comment]
Any news on this? @arcpato

**Comment by arcpato** [comment]
Pagination is off, Browser Chrome and IE. I have a data set I can email you.

**Comment by mdwragg** [comment]
Same performance on IE and Chrome? Can you share some figures please, that would seem unlikely.

**Comment by mdwragg** [comment]
Closing due to age and lack of required information.
