### ISSUE TITLE
Not printing column values if the column heading includes whitespaces

### ISSUE THREAD

**Issue by Adeel-Abdullah** [PredixDev/px-data-table#70]
# Submit an Issue

If the column heading or the property of the javascript object contains a whitespace the table does not print the property values for that property

## Screenshots (_optional, but very helpful_):
![px-data-table error](https://cloud.githubusercontent.com/assets/11469667/19920535/1bd3c468-a0fb-11e6-9a87-354885dd921b.PNG)

#codepen link:
http://codepen.io/anon/pen/pNoeYv?editors=1001

As you can see the "first Name" and "last Name" columns do not print at all while the email column prints as expected, as far as I've been able to figure out it's because the column names"first Name" and "last Name" include whitespaces in them while "email" does not

**Comment by mdwragg** [comment]
Hi, can you provide a codepen/fiddle showing this issue? And detailed description on how to recreate.

Thanks.

**Comment by Adeel-Abdullah** [comment]
Codepen has been added, please do take a look.

**Comment by Adeel-Abdullah** [comment]
Hello,
Any updates? Can you confirm the issue.

Thanks

**Comment by mdwragg** [comment]
Fixed in v1.14.5
