### ISSUE TITLE
Need formatString property on px-data-table-column to easily format Date strings

### ISSUE THREAD

**Issue by michgrady** [PredixDev/px-data-table#76]
I'd expect that the px-data-table-column would have a 'formatString' property or similar to allow an easy way to format a Date string coming in from server side.  

For example, this is so that a service can return data in ISO format, but then in data table, might just want to show date portion (and not time).    

Also we need to consider localization with something like this, so property would need to be bindable since format could be dependent on locale.

FYI, I found this same issue on Predix forum so looks like others have faced this issue as well. 
https://forum.predix.io/questions/2727/how-to-format-date-on-px-data-table.html

**Comment by mdwragg** [comment]
Hi the data table simply displays string data - your application can format the strings as it pleases prior to piping the data to the table.

**Comment by mdwragg** [comment]
Closing this as the trail seems to have gone cold, hopefully you figured out how to transform the strings on your client prior to piping the data to the data table. Thanks for your question.
