### ISSUE TITLE
Bit of code in aha table won't run

### ISSUE THREAD

**Issue by benoitjchevalier** [PredixDev/px-data-table#77]
[this line in aha table](https://github.com/PredixDev/px-data-table/blob/master/aha-table.html#L497) expects an "evt" var which is never declared. The validation won't run. Not sure what the consequences are (appart from console exceptions: Uncaught ReferenceError: evt is not defined(…)).

Been able to have the console errors fire in the local demos by changing a value in a dropdown in a cell.

introduced a while ago by [this commit](https://github.com/PredixDev/px-data-table/commit/44f39c591c6e79d9473a0c92ef68735cd8273acf)

noticed on current latest datatable: 0.14.12

**Comment by randyaskin** [comment]
I believe this is fixed in 2.0.0
