### ISSUE TITLE
Not able to sort by date with px-data-table

### ISSUE THREAD

**Issue by benmak11** [PredixDev/px-data-table#78]
have data with dates 11/1/2016, 11/2/2016, 11/3/2016, 11/11/2016, 11/21/2016 etc. When I do the sorting, then it is sorted as follows:
11/1/2016
11/11/2016
11/2/2016
11/21/2016
11/3/2016

Instead of
11/1/2016
11/2/2016
11/3/2016
11/11/2016
11/21/2016

What to find out if we can insert some property to allow sorting by type rather than converting all json object keys and values to strings.

**Comment by mdwragg** [comment]
Hi,

I don't understand what this means "What to find out if we can insert some property to allow sorting by type rather than converting all json object keys and values to strings."

Have you seen the custom sort function support here: https://predixdev.github.io/px-data-table/px-data-table/px-data-table-column-demo.html ?

Thanks,
Martin.

**Comment by benmak11** [comment]
Hi @mdwragg,

Yes, I have seen that page but I would want to be able to sort by the data type being spit back by my API calls in the JSON. Right now I have the Date datatypes coming back which I should be able to sort through accordingly with the sort functionality of the grid. The options that come from the ps-data-table-column's type property are string, html and dropdown.

Does this make sense?

**Comment by mdwragg** [comment]
Hi, so if I understand correctly you're asking the column to be extended to support Date types out of the box?

**Comment by benmak11** [comment]
Yes, that's it.

**Comment by kentcabarle** [comment]
Are there any updates/new for the fix for this issue? Thanks.

**Comment by mdwragg** [comment]
Closing 'cause sort mechanism proposed is the correct way to do this.
