### ISSUE TITLE
Not updated versions in bower.json cause inconsistent build results for different developers

### ISSUE THREAD

**Issue by simonovdenis** [PredixDev/px-data-table#84]
# Submit an Issue
Generated html files with CSS styles(in CSS folder) in version 1.15.1 are missing few custom CSS properties, which were existing in previous version.

## Expected behavior and actual behavior:
Generated html files with CSS styles(in CSS folder) in version 1.15.1 should at least contain previously existed custom CSS properties, which were in these files in previous version.

## Steps to reproduce the problem:
This can easily reproduced with building of these files from sass ones using gulp. With dependencies resolved from currently committed bower.json and no latest dependencies versions already existing in your local repo(cached) you'd see result as one committed. To fix the issue and not to loose custom CSS properties, dependencies versions in bower.json have to be updated to later(latest?) versions - at least to ones, where static css styles were replaced with custom CSS properties(--px-XXX)

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
px-data-table 1.15.1

## Code examples help us better understand the issue - follow the appropriate codepen for the component by going to https://predix-ui.com, finding the component in question, and clicking on the pencil icon under the demo.
        Once you've created your code example, you can save it under a new url.
        Please note that you should NOT use the same methods for production as the ones used in codepen - these methods are not production ready.

**Comment by mdwragg** [comment]
Hi, can you help us by spelling out which custom CSS properties you are missing? Thanks.

**Comment by simonovdenis** [comment]
From only 1 file - aha-table-styles.html(the rest of them are missing similar set of props):
--px-base-background-color
--px-input-border-color--outer
--px-input-border-color--inner
--px-input-background-color
--px-input-text-color
--px-input-border-color--readonly
--px-input-background-color--readonly
--px-input-text-color--readonly
--px-input-border-color--disabled
--px-input-background-color--disabled
--px-input-text-color--disabled
--px-input-border-color--outer--focused
--px-input-border-color--inner--focused
--px-input-text-color--placeholder
--px-input-text-color--placeholder
--px-select-shadow-color--light
--px-select-background-color
--px-select-text-color
--px-select-border-color--hover
--px-select-background-color--hover
--px-select-border-color--pressed
--px-select-background-color--pressed
--px-select-text-color--disabled
--px-select-background-color--disabled
--px-input-border-color--outer
--px-multiselect-background-color
--px-input-text-color--help
--px-validation-warning-text-color
--px-validation-error-text-color
--px-validation-success-text-color
--px-validation-warning-text-color
--px-validation-error-text-color
--px-validation-success-text-color
--px-btn-border-color
--px-btn-shadow--light
--px-btn-background
--px-btn-color
--px-btn-border-color--hover
--px-btn-shadow
--px-btn-background--hover
--px-btn-border-color--pressed
--px-btn-background--pressed
--px-btn-bare-color--visited
--px-btn-bare-color--hover
--px-btn-bare-color--pressed
--px-btn-primary-border-color
--px-btn-shadow
--px-btn-primary-background
--px-btn-primary-color
--px-btn-primary-background--hover
--px-btn-primary-background--pressed
--px-btn-disabled-border-color
--px-btn-disabled-background
--px-btn-disabled-color

As for the rest - please just use some tool, that can show diff(look into css/*.html files), between 2 commits below:
9ee4a15 Martin Wragg on 12.12.2016 at 20:32 Fixed striping table row style
e640f87 Randy Askin on 06.12.2016 at 18:22 added style variables for header row

**Comment by mdwragg** [comment]
These should be back now, assuming I understand your issue. 👍
