### ISSUE TITLE
px-data-table select all indicates all records selected rather than filtered records when table filtered.

### ISSUE THREAD

**Issue by jkirkwood-bitstew** [PredixDev/px-data-table#86]
## Expected Behavior
When data table is filtered and the user clicks the "Select All" checkbox it should select only the records that are visible / available while filtered. 

## Actual Behavior
When select all is checked it indicates that 22 records are selected when only 7 match my filter. If you clear the filter all the records are selected.

## Steps to reproduce the problem:
- Install Predix UI Seed
- Navigate to Parent Asset
- Select Data Table View
- Filter CurrentReading to 0.88
- Click Select All

## Environment:
- **Version**: v1.14.22
- **Browser**: Chrome version 54.0.2840.99 
- **Operating System**: Windows 10 Professional

**Comment by austinmcdaniel** [comment]
related to this: select all with pagination selects everything, rather than just the current page of items. Items that are not on the current page should not be selected.

**Comment by randyaskin** [comment]
Fixed in v2.1.1. Thanks for the PR @caseyliss !
