### ISSUE TITLE
Pencil icon not shown in editable columns

### ISSUE THREAD

**Issue by simonovdenis** [PredixDev/px-data-table#88]
In editable columns:
1. Pencil icon not shown in editable columns.
2. Column widths change on mouse over(probably trying to show icon above).

## Expected behavior and actual behavior:
1. Pencil icon should be shown in editable columns.
2. Column widths have to be the same with and without icon.

## Steps to reproduce the problem:
Create table with 1 or more editable columns. Width of column is a bit more than width of it's content. 

## Code examples help us better understand the issue - follow the appropriate codepen for the component by going to https://predix-ui.com, finding the component in question, and clicking on the pencil icon under the demo.
        http://codepen.io/anon/pen/xRNKEq?editors=1011

PS: fix for icon consists in changing prefixes for icons(polymer-font-awesome => fa) in _getCellIcon method in px-data-table-cell.html to:
_getCellIcon: function(showEditIcon, editing, valid){
        if(valid) {
          if(showEditIcon) {
            return 'fa:fa-pencil';
          }
        }
        else {
          return 'fa:fa-warning';
        }
      }

**Comment by mdwragg** [comment]
Hi,

Thanks for the issue. Working for me fine here: https://www.predix-ui.com/px-data-table/px-data-table/px-data-table-column-demo.html (build from latest release of px-data-table).

Can you please check the link above and close if it works for you, thanks!

**Comment by simonovdenis** [comment]
Sorry, cannot close. Yes, with this demo it works, but you can easily reproduce the issue wth this demo:

- click on the pencil icon in this demo to go to codepen(right bottom corner of screen)

- change table-data={{data}} with table-data='[{"first":"Valentine","last":"Meyer","email":"valentinemeyer@scentric.com"},{"first":"Silva","last":"Alexander","email":"silvaalexander@gmail.com"},{"first":"Hopkins","last":"Wong","email":"hopkinswong@hotmail.com"}]'

- change only 1 column shown to following 3:
<px-data-table-column name="first" editable="true" type="string"></px-data-table-column>
  <px-data-table-column name="last" editable="true" type="string"></px-data-table-column>
  <px-data-table-column name="email" editable="true" type="string"></px-data-table-column>

The issue is reproducible...

**Comment by nonmetalhail** [comment]
<img width="969" alt="screen shot 2016-12-28 at 2 41 27 am" src="https://cloud.githubusercontent.com/assets/1649404/21520173/4b1f6bf0-cca7-11e6-882a-4f7e45b18693.png">

This would explain why it is not showing up in the CodePen. Do you see this issue anywhere other than the CodePen?

**Comment by simonovdenis** [comment]
Ok, this really explains codepen issue. But I have the same behavior locally with latest table component. As I've said before fixing prefix to 'fa' solves the issue. All iron-icon components, that I've seen, use this prefix. Only here there's other one - 'polymer-font-awesome'. 
In px-polymer-font-awesome/polymer-font-awesome-all.html and px-polymer-font-awesome/polymer-font-awesome.html:
iron-iconset-svg id="fa" name="fa"
Maybe there's some code, that performs translation?
BTW I have latest version of px-polymer-font-awesome -  1.1.0

**Comment by runn-vermel** [comment]
Hi @simonovdenis 

Thanks for the issue - this should be fixed in v1.15.4
