### ISSUE TITLE
aha-table-styles.html includes Font-Awesome not relative to bower components

### ISSUE THREAD

**Issue by jonniespratley** [PredixDev/px-data-table#93]
The aha-table-styles.html includes inline styles that reference font-awesome but it makes 404 appear.
```
http://localhost:5050/bower_components/px-data-table/font-awesome/fonts/fontawesome-webfont.ttf?v=4.4.0 404 (Not Found)
```

Path should be` ../../` and not `../`

**Comment by runn-vermel** [comment]
hi @jonniespratley - wanna give us a link that isn't on your localhost? ;)

**Comment by jonniespratley** [comment]
@runn-vermel Sure, I guess I can setup a codepen

**Comment by jonniespratley** [comment]
Hmm here is a link to a CodePen http://s.codepen.io/jonniespratley/debug/vggyqm

For some reason the error is not displaying, I have updated locally to the latest version, and I get the error, but not on the CodePen.

**Comment by randyaskin** [comment]
It shows up in our Travis logs as well: https://travis-ci.org/PredixDev/px-data-table/builds/193152039#L1527

**Comment by mtbradle-ge** [comment]
Any update on this issue? I am seeing this error as well.

**Comment by mdwragg** [comment]
@mtbradle-ge @jonniespratley - can you provide me with a repo I can run up and instructions to recreate this? I'm struggling to find a reliable way to make this happen.

What browser are you seeing this in too?

Thanks.

**Comment by ronaldsankey** [comment]
This is still an issue.  The style sheet just needs to be updated to go up an additional level.  Change ../font-awesome to ../../font-awesome.     The px-modal component has the exact same issue, as well.

**Comment by mdwragg** [comment]
@ronaldsankey - I need to recreate it to fix it, and test that the fix works. When I say _"I'm struggling to find a reliable way to make this happen."_ I'm not saying it for the sake of it.

**Comment by mdwragg** [comment]
Hi, @anundinesh has just reported the same thing - can somebody on this thread please get back to me with how you are seeing this issue? (ideally a sandboxed repo with instructions to recreate it e.g. "clone the repo, run http_serve, open console, see the errors")

We don't see it locally via `gulp serve`, `polymer serve`, or via static web server on the seed app, predix-ui.com etc.

Thanks.

**Comment by anundinesh** [comment]
You can refer your own codepen for data table http://codepen.io/pen/?editors=1000, same error. I'm using chrome browser.

**Comment by mdwragg** [comment]
That codepen is empty @anundinesh ...

**Comment by randyaskin** [comment]
I think their point was you could navigate from the CodePen link on the px-data-table demo page (which results in a "blank" codepen from a URL perspective, since we build them dynamically).

**Comment by mdwragg** [comment]
Ah.

**Comment by anundinesh** [comment]
Any word on this?

**Comment by mdwragg** [comment]
Hi, can you please create me a repo to recreate this? While I can see the 404s in the codepen, I can't recompile the sass to test a fix...

**Comment by mdwragg** [comment]
Or at least give me instructions to set my own env up to recreate. Thanks.

**Comment by mdwragg** [comment]
Did you see the above replies @anundinesh? We need your help recreating this please!

**Comment by anundinesh** [comment]
Basically unable to recreate the same issue, because code pen created for Data table was showing the same error which i got and shared. Right now I've checked same in the codepen no errors. I'm bit clueless may be i guess because of new built.

**Comment by mtbradle-ge** [comment]
Been living with this error for months but hadn't found time to bother with it. But finally here is a repo with the bare minimum to reproduce the error:

https://github.com/mtbradle-ge/px-data-table-issue-93

Just `bower install` and `polymer test`

Errors should show up in the console and in the browser dev tools. Tested on latest Chrome (58.0.3029.81)

**Comment by mdwragg** [comment]
💯 @mtbradle-ge 👏 Thanks!

**Comment by mtbradle-ge** [comment]
Thanks for the quick fix! I was still seeing this error in our test suite, but turns out, we had our own generated styles referencing font-awesome as well. I was able to use the same fix (configuring `$fa-font-path` in our sass).

Neat :)

**Comment by mdwragg** [comment]
Awesome - thanks for the feedback @mtbradle-ge. Yeah, that sass variable is a useful one! Sadly the sass partial can't second guess every place it'll be embedded in a css build. Weirdly we don't see it through running it up locally/in our test bed apps.

With the redesign we're going through right now for the Predix Design System, we're looking to pull these loading of web fonts out of components. Icons will be SVG and GE fonts will be applied uniformly via a theme. This should save a good number of slow/cumbersome requests on a per-component basis.

👍
