### ISSUE TITLE
Padding is wrong for filterable & editable columns

### ISSUE THREAD

**Issue by randyaskin** [PredixDev/px-data-table#95]
#### Expected behavior and actual behavior:
On the px-data-table-column demo page, the padding is off in the first column. The combination of filterable/editable may be the culprit?

#### Browsers / Environments
Any/All

#### Steps to reproduce the problem:
https://www.predix-ui.com/px-data-table/px-data-table/px-data-table-column-demo.html

#### Screenshots (_optional, but very helpful_):
![screen shot 2017-01-25 at 2 47 24 pm](https://cloud.githubusercontent.com/assets/2130613/22312655/a64183ac-e30d-11e6-8045-e573cd030da7.png)

**Comment by mdwragg** [comment]
Fixed by 147f08a26b8e328dea11be09c0fcd234bcf59a20
