### ISSUE TITLE
Not able to sort properly using px-data-table-column type="html"

### ISSUE THREAD

**Issue by DipenV** [PredixDev/px-data-table#96]
# Submit an Issue

Hi,

We are facing issue in sorting the px-data-table-column having type as "html".
Our html statement for each row consist of status icon and AssetName wrapped under div and span to display with required font and style.
But the problem seems that the sorting considers the complete html and not the AssetName on the basis of which we want to sort in ascending and descending.

## Expected behavior and actual behavior:
Expected behavior:
Sorting to support based on the text displayed.

Actual behavior:
Sorting based on the complete html statement.

## Steps to reproduce the problem:
<px-data-table hide-pagination-control id="assetTable" table-data="{{tableData}}" table-rows="true">
<px-data-table-column type="html" name="{{item}}" sortable="true"></px-data-table-column>
</px-data-table>

Sortable column consist of below code
![image](https://cloud.githubusercontent.com/assets/25501769/22545979/043c71a2-e961-11e6-8e26-b339a0aa6d25.png)

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
px-data-table version: 1.15.0

## Screenshots (_optional, but very helpful_):
![image](https://cloud.githubusercontent.com/assets/25501769/22545709/ce817d92-e95f-11e6-873c-f2a18cffffa6.png)

![image](https://cloud.githubusercontent.com/assets/25501769/22545741/f2c9aef4-e95f-11e6-9d16-6184b1500a80.png)

**Comment by mdwragg** [comment]
Hi. Are you specifying a custom sort function? Default sort functionality is to sort according to the whole content of the cell. You may have to override this for your example...

Check out the API docs here: https://www.predix-ui.com/px-data-table/px-data-table/px-data-table-column-demo.html (sort function).

**Comment by mdwragg** [comment]
Guessing no reply means that the docs got you up and running? I'll close this issue then. Please let us know if you still can't figure it out. Thanks.
