### ISSUE TITLE
Would be useful to allow for one item to be selected (radio-button) rather than only multiple.

### ISSUE THREAD

**Issue by jasongill-ge** [PredixDev/px-data-table#99]
I would like to use the px-data-table for our Predix component, however, I need to select a single row instead of multiple.  If I disable selectable, then no items can be selected, if enabled, then I only get check boxes rather than radio.

**Comment by randyaskin** [comment]
Added in 2.0.0 - new boolean property single-select can be used to switch from multi-select (checkboxes) to single (radio button).
